FROM ubuntu

# Install system dependencies
RUN apt-get update && \
    apt-get install -y ffmpeg python3 python3-pip python3-venv && \
    apt-get clean

# Create a virtual environment and install Python packages
RUN python3 -m venv /venv && \
    /venv/bin/pip install --upgrade pip setuptools && \
    /venv/bin/pip install openai-whisper setuptools-rust

# Set the virtual environment as the default Python environment
ENV PATH="/venv/bin:$PATH"

ENTRYPOINT [ "bash" ]
